RogueAssassination bleed modifiers, shadow dacne
Hekili/hekili pull request #2083
Opened 2022-12-04 13:02 UTC by IIeTpoc

Nightstalker only boosts damage by 8% now and Subterfuge does not boost Garrote damage anymore. https://www.wowhead.com/spell=14062/nightstalker#changelog https://www.wowhead.com/spell=108208/subterfuge#changelog

Improved Garrote has 2 different IDs thus multiplier should be calculated in stealth properly aswell.

Shadow dance now has 6 seconds uptime and is not affected by talents for Assa and Outlaw at least.

Garrote cp_gain is affected not only by stealth but also by talent improved garrote itself which can be used without being specced to subterfuge

2022-12-04 15:48 UTC, Hekili requested changes
Just need one minor fix and it's good to go.

2022-12-04 15:48 UTC, Hekili commented on Dragonflight/RogueAssassination.lua
> +    if FindPlayerAuraByID( 392401 ) or FindPlayerAuraByID( 392403 ) and spellID == 703 then
Need parentheses around the FindPlayerAuraByID calls:

`if ( FindPlayerAuraByID( 392401 ) or FindPlayerAuraByID( 392403 ) ) and spellID == 703 then`

2022-12-04 20:20 UTC, IIeTpoc commented
Thanks! I have done this change now, but i do not know how to close that change request from you

2022-12-07 20:46 UTC, Hekili approved these changes

2022-12-07 20:46 UTC, merged