quick fixes, non-anniversary
Hekili/hekili pull request #4006
Opened 2024-10-22 13:40 UTC by syrifgit

spreist MF:I
resto sham old pack string (fixes healing helper)

2024-10-22 13:55 UTC, Hekili requested changes
Quick fixes to PriestShadow; please import if can.

2024-10-22 13:55 UTC, Hekili commented on TheWarWithin/Priorities/PriestShadow.simc
> +actions.empowered_filler+=/mind_flay_insanity,cycle_targets=1,,if=buff.mind_flay_insanity.up
1 comma.

2024-10-22 13:55 UTC, Hekili commented on TheWarWithin/Priorities/PriestShadow.simc
>  actions.empowered_filler+=/mind_spike_insanity,cycle_targets=1
Please add `,if=buff.mind_spike_insanity.up` (for the same reason the Mind Flay change is needed below.

2024-10-22 13:58 UTC, syrifgit commented
Done. Servers are down, will need to make a list of pack strings to generate once servers are up for anything we do from this point on.

Unless we can convince someone on EU to do it.

2024-10-23 01:13 UTC, Hekili approved these changes

2024-10-23 01:13 UTC, merged